Make tests pass in 2020
moving this beyond 2038 requires fixes on 32-bit systems to avoid errors:
   File "/home/abuild/rpmbuild/BUILD/python3-saml-1.6.0/src/onelogin/sam
.py", line 419, in parse_SAML_to_time
     data = datetime.strptime(timestr, '%Y-%m-%dT%H:%M:%SZ')
 TypeError: strptime() argument 1 must be string, not long