return_false_on_exception: only catch OneLogin SAML specific exceptions
Instead of hiding any exception, hide OneLogin SAML specific exceptions
so that any other errors (for example, xmlsec is unable to load the
certificate) are passed through. It's often better to pass these through
and possibly cause internal server error to be displayed. Alternatively,
user (and administrator) would see confusing, unrelated error message
which makes finding the root cause very difficult.